#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias git=hub
PATH=$PATH:/home/oscar/.gem/ruby/2.2.0/bin:/home/oscar/.bin

stty -ixon
alias pip=pip-save

autoload -Uz promptinit
promptinit
prompt cloud ❯
