#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias t='t --task-dir ~/Drive --list tasks'
alias ls='ls --group-directories-first --color=auto -N'

stty -ixon

export TERM='xterm-256color'

(cat ~/.cache/wal/sequences &)
